# Generated by Django 3.1.7 on 2021-03-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('comment', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
