# Generated by Django 3.1.7 on 2021-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='item',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
