# Generated by Django 3.1.7 on 2021-04-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoRestful', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoRestfulModel',
        ),
    ]
