# Generated by Django 3.1.7 on 2021-04-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoRestful', '0002_auto_20210424_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='todorestfulmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
