# Generated by Django 3.1.7 on 2021-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
